version: 2.1

default: &defaults
  docker:
    - image: circleci/python
    
jobs:
  build:
    <<: *defaults
    parameters:
      argument:
      #  description: the argument to run the command against
        type: string
        
    steps:
      - run :
          name: Command for << parameters.argument >>
          command: |
              echo << parameters.argument >>
              
  test:
    docker:
      - image: circleci/python
    steps:
      - run :
          name: Testing
          command: |
              echo "I'm testing"
      
  cleanup:
    docker:
      - image: circleci/python
    steps:
      - run :
          name: Cleaning Everything
          command: |
              echo "I'm cleaning up" 
      
workflows:
  workflow:
    jobs:
      - build:
          name: Build << matrix.argument >>
          matrix:
            parameters:
              argument: ["macos", "windows", "linux"]
              
              
      - test:
          name: Test
          requires:
            - build
            
      - cleanup:
          requires:
            - test
