version: 2.1

#### This is the forkeeeeeeeee

jobs:
  build:
    parameters:
      argument:
        description: the argument to run the command against
        type: string
        
    docker:
      - image: circleci/python
    steps:
      - run :
          name: Command for << parameters.argument >>
          command: |
              echo << parameters.argument >>
              
  test:
    parameters:
      argument:
        description: the argument to run the test against
        type: string
        
    docker:
      - image: circleci/python
    steps:
      - run :
          name: Testing << parameters.argument >>
          command: |
              echo "I'm testing << parameters.argument >>"
      
      
workflows:
  workflow:
    jobs:
      - build:
          name: Build << matrix.argument >>
          matrix:
            parameters:
              argument: ["macos", "windows", "linux"]
              
              
      - test:
          name: Test << matrix.argument >>
          matrix:
            parameters:
              argument: ["macos", "windows", "linux"]
          requires:
            - Build << matrix.argument >>
