version: 2.1

default: &default
  executor:
    docker:
      - image: circleci/python
jobs:
  build:
    parameters:
      argument:
      #  description: the argument to run the command against
        type: string
        
    <<: *defaults
    steps:
      - run :
          name: Command for << parameters.argument >>
          command: |
              echo << parameters.argument >>
              
  test:
    parameters:
      argument:
      #  description: the argument to run the test against
        type: string
        
    docker:
      - image: circleci/python
    steps:
      - run :
          name: Testing << parameters.argument >>
          command: |
              echo "I'm testing << parameters.argument >>"
      
  cleanup:
    docker:
      - image: circleci/python
    steps:
      - run :
          name: Cleaning Everything
          command: |
              echo "I'm cleaning up" 
      
workflows:
  workflow:
    jobs:
      - build:
          name: Build << matrix.argument >>
          matrix:
            parameters:
              argument: ["macos", "windows", "linux"]
              
              
      - test:
          name: Test << matrix.argument >>
          matrix:
            parameters:
              argument: ["macos", "windows", "linux"]
          requires:
            - Build << matrix.argument >>
            
      - cleanup:
          requires:
            - test
